config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :who_likes] do
    resources :likes, only: [:create, :destroy]
    member do
      get :who_likes
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :event_invites
  resources :events do
    collection do
      get :old
    end
    resources :event_comments, only: [:create, :destroy]
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new', via: :get
  match '/forgotten_password', to: 'users#forgotten_password', via: :get
  match '/send_password_link', to: 'users#send_password_link', via: :post
  match '/reset_password/:uuid', to: 'users#show_reset_password', via: :get
  match '/reset_password', to: 'users#reset_password', via: :post
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help', via: :get
  match '/contact', to: 'static_pages#contact', via: :get
  match '/about', to: 'static_pages#about', via: :get

end

app/models/user.rb
class User < ActiveRecord::Base

  # attr_accessible :name, :email, :password, :password_confirmation, :username
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :events
  has_many :event_invites
  has_many :events, through: :event_invites
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  before_save { |user| user.email = user.email.downcase
                       user.username = user.username.downcase}
  before_save :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  VALID_USERNAME_REGEX = /\A\w+\z/
  validates :username, presence: true, length: {maximum: 15, minimum: 2}, format: {with: VALID_USERNAME_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}
  validates :password_confirmation, presence: true

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def likes?(micropost)
    likes.find_by_micropost_id(micropost.id)
  end

  def feed
    Micropost.includes(:user).includes(:likes).includes(:likes => :user).references(:likes, :user).from_users_followed_by(self)
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper, MailHelper

  before_filter :signed_in_user, only: [:index, :show, :edit, :update, :destroy, :following, :followers]
  before_filter :signed_out_user, only: [:forgotten_password, :send_password_link, :show_reset_password, :reset_password]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
    @codeword = Codeword.new
  end

  def create
    @user = User.new(user_params)
    @codeword = Codeword.new(codeword_param)
    if @user.valid? & existing_codeword?(@codeword)
      @user.save
      sign_in @user
      flash[:success] = 'Welcome to TwittoSocial!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      sign_in @user
      flash[:success] = 'User was updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_path
  end

  def forgotten_password
  end

  def send_password_link
    user = User.find_by_email(params[:user][:email].downcase)
    if user
      token = SecureRandom.urlsafe_base64
      user.update_attribute(:forgotten_password_key, token)
      send_forgot_password_message(user.email, token)
      flash[:success] = 'Check your email'
      redirect_to signin_path
    else
      flash.now[:error] = 'Email not found'
      render 'forgotten_password'
    end
  end

  def show_reset_password
    @user = User.find_by_forgotten_password_key(params[:uuid])
    if @user.nil?
      flash[:error] = 'Usertoken could not be found. Try resending the password for your user'
      redirect_to forgotten_password_path
    end
  end

  def reset_password
    @user = User.find_by_forgotten_password_key(params[:forgotten_password_key]) if params[:forgotten_password_key]
    if @user
      if @user.update_attributes(params[:user])
        @user.update_attribute(:forgotten_password_key, nil)
        sign_in @user
        flash[:success] = 'New password was set. Welcome inside!'
        redirect_to root_path
      else
        render 'show_reset_password'
      end
    else
      flash[:error] = 'Usertoken could not be found.'
      render 'forgotten_password'
    end
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def codeword_param
    params.require(:codeword).permit(:codeword)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user
  def gravatar_for(user, options = {size: 50, image_icon: 'monsterid'})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}&d=#{options[:image_icon]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def existing_codeword?(codeword)
    exist = Codeword.where('codeword = ?', codeword.codeword).to_a.size > 0
    unless exist
      codeword.errors.add(:codeword, "is needed to create a user. Only the chosen ones will have it")
    end
    exist
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
    <div>
      <%= f.hidden_field :followed_id %>
    </div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user), html: {method: :delete}, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, options = {size: 50, image_icon: 'monsterid'} %>
  <%= link_to user.name, user %> <span class="username">@<%= user.username %></span>
  <% if @user_rank[user.id] %> <div class="app-icon <%= rank_color_class(@user_rank[user.id]) %>" title="Rank based on activity the latest month"></div><% end %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to 'delete', user, method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: @user %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= gravatar_for @user  %>
    <a href="http://gravatar.com/emails" target='_blank'>change</a>
  </div>
</div>

app/views/users/forgotten_password.html.erb
<% provide(:title, 'Forgot password') %>
<h1>Forgot password</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(:user, url: send_password_link_path) do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.submit 'Send', class: 'btn btn-large btn-primary' %>

    <% end %>
    <p>New user? <%= link_to 'Sign up now!', signup_path %></p>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
        <%= render 'shared/multiple_form_error_messages' %>
        <%= fields_for @codeword do |c| %>
            <%= c.label :codeword, 'Secret code word' %>
            <%= c.text_field :codeword %>
        <% end %>
        <%= f.label :name, 'Fullname' %>
        <%= f.text_field :name %>

        <%= f.label :username %>
        <%= f.text_field :username %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit 'Create my account', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/reset_password_mail.html.erb
<h2 style="font-weight:300;line-height:1.2em;text-align:center" align="center">
  <br>
  Reset password
  <br>
</h2>
<p>Hey there</p>
<p>Click <a href='<%= get_url %>/reset_password/<%= token %>' target='_blank' style='color:#007fb6;text-decoration:none'>here</a> to set your new password</p>
<p style="margin-bottom:0">

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <% if !@user.username.nil? %><span class="username">@<%=@user.username %></span><% end %>
      <% if @user_rank[@user.id] %> <div class="app-icon <%= rank_color_class(@user_rank[@user.id]) %>" title="Rank based on activity the latest month"></div><% end %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'users/follow_form' if signed_in? %>
    <% if @user.microposts.any? %>
        <h3>Microposts <%= @user.microposts.count %></h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30, image_icon: 'monsterid'), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/show_reset_password.html.erb
<% provide(:title, 'Edit user') %>
<h1>Change password</h1>

<div class="row">
  <div class="span6 offset3">
    <h3>Hi there <%= @user.name unless @user.nil? %></h3>
    <br/>
    <%= form_for(:user, url: reset_password_path) do |f| %>
        <%= render 'shared/error_messages', object: @user %>
        <%= hidden_field_tag :forgotten_password_key, @user.forgotten_password_key %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, 'Confirm Password' %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit 'Save password', class: 'btn btn-large btn-primary' %>
    <% end %>

  </div>
</div>