config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :who_likes] do
    resources :likes, only: [:create, :destroy]
    member do
      get :who_likes
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :event_invites
  resources :events do
    collection do
      get :old
    end
    resources :event_comments, only: [:create, :destroy]
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new', via: :get
  match '/forgotten_password', to: 'users#forgotten_password', via: :get
  match '/send_password_link', to: 'users#send_password_link', via: :post
  match '/reset_password/:uuid', to: 'users#show_reset_password', via: :get
  match '/reset_password', to: 'users#reset_password', via: :post
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help', via: :get
  match '/contact', to: 'static_pages#contact', via: :get
  match '/about', to: 'static_pages#about', via: :get

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_invites
  has_many :users, through: :event_invites, validate: false
  has_many :event_comments
  belongs_to :user

  validates :title, presence: true, length: {maximum: 250}
  validates_presence_of :start_time, :end_time
  validates :invitation, presence: true, length: {maximum: 3000}
  validates :user_id, presence: true
  validate :start_time_before_end_time

  private

  def start_time_before_end_time
    if start_time && end_time && start_time > end_time
      errors.add(:start_time, 'Start time must be before end time')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  before_filter :signed_in_user
  before_filter :user_is_invited, only: [:edit, :update, :destroy, :show]
  before_filter :user_can_update, only: [:edit, :update, :destroy]

  def index
    @events = Event.joins(:event_invites)
                  .where('end_time > ? and event_invites.user_id = ?', DateTime.now, current_user.id)
                  .paginate(page: params[:page]).order('start_time')
  end

  def old
    @events = Event.joins(:event_invites)
                  .where('end_time < ? and event_invites.user_id = ?', DateTime.now, current_user.id)
                  .paginate(page: params[:page], per_page: 10).order('start_time desc')
  end

  def show
    @event = Event.includes(:event_invites => :user).references(:event_invites, :user).find(params[:id])
    @event_comment = EventComment.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.user = current_user
    if @event.save
      @event.event_invites.create(user_id: current_user.id, attend_status: 'yes')
      if @event.send_mail
        send_email_to_all_invites(@event)
      end
      flash[:success] = 'Event created!'
      redirect_to events_path
    else
      @feed_items = []
      @usernames = User.all.collect { |user| user.username.to_s }.sort
      render 'new'
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      @event.event_invites.create(user_id: current_user.id, attend_status: 'yes')
      if @event.send_mail
        send_email_to_all_invites(@event)
      end
      flash[:success] = 'Event was updated'
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def destroy
    if Event.find(params[:id]).user_id == current_user.id
      EventComment.where('event_id = ?', params[:id]).delete_all
      EventInvite.where('event_id = ?', params[:id]).delete_all
      Event.find(params[:id]).delete
      flash[:success] = 'Event deleted'
    end
    redirect_to events_path
  end

  def join
    Rails.logger.error("JOIN")
  end

  def maybe
    Rails.logger.error("MAYBE")
  end

  def decline
    Rails.logger.error("DECLINE")
  end

  private

  def user_is_invited
    if Event.includes(:event_invites).references(:event_invites).where('events.id = ? and event_invites.user_id = ?', params[:id], current_user.id).length == 0
      flash[:warning] = 'You have no access to this event!'
      redirect_to events_path
    end
  end

  def user_can_update
    if current_user.admin
      @event = Event.find_by_id(params[:id])
    else
      @event = current_user.events.find_by_id(params[:id])
    end
    redirect_to event_path if @event.nil?
  end

  def event_params
    params.require(:event).permit(:title, :location, :start_time, :end_time, :invitation, :send_mail, :invite_all, :user_id, :user_ids => [])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  include MailHelper

  def send_email_to_all_invites(event)
    all_emails = all_invites(event)
    all_emails << event.user.email
    Rails.logger.info("Trying to send event invite to #{all_emails.join(',')}")
    send_event_invite(all_emails, "#{event.user.name} invited you to #{event.title}")
  end

  def all_invites(event)
    event.users.collect { |user|
      user.email
    }
  end

  def get_url
    request.protocol + request.host_with_port
  end

end

app/views/events/_add_invites.html.erb
<% if !@users.empty? %>
    <ul class="users">
      <% @users.each do |user| %>
          <li>
            <%= gravatar_for user, options = {size: 50, image_icon: 'monsterid'} %>
            <%= link_to user.name, user %>
          </li>
      <% end %>
    </ul>
<% end %>

app/views/events/_attend_overview.html.erb
(<%= event_invites.find_all { |ei| ei.attend_status == 'yes' || ei.attend_status == 'maybe' }.count %>/<%= event_invites.count %> <i class="icon-info-sign"></i>)

app/views/events/_attend_status.html.erb
<% if status == 'maybe' %>
    <span class="label label-warning">Maybe</span>
<% elsif status == 'yes' %>
    <span class="label label-success">Attending</span>
<% elsif status == 'no' %>
    <span class="label label-important">Not attending</span>
<% else %>
    <span class="label">Awaiting reply</span>
<% end %>

app/views/events/_attend_status_list.html.erb
<p>
  <span class="event-label">People:</span>
</p>
<ul class="event-attendees">
  <li>
    <%= form_for(@event.event_invites.find_by_user_id(current_user.id), html: {class: 'no-margin'}, remote: true) do |f| %>
        You - <%= f.submit 'Join', class: 'submitLink' %>
        -
        <%= f.submit 'Maybe', class: 'submitLink' %>
        -
        <%= f.submit 'Decline', class: 'submitLink' %> -
        <div id="event-reply-status-<%= @event.id %>" class='no_clear'><%= render partial: 'events/attend_status', locals: {status: @event.event_invites.find_by_user_id(current_user.id).attend_status} %> </div>
    <% end %></li>
  <% @event.event_invites.sort { |a, b| a.user.name.upcase <=> b.user.name.upcase }.each do |i| %>
      <% unless current_user?(i.user) %>
          <li><%= i.user.name %><span class="username">(@<%= i.user.username %>
            )<span> - <%= render partial: 'events/attend_status', locals: {status: i.attend_status} %></li>
      <% end %>
  <% end %>
</ul>

app/views/events/_event.html.erb
<hr>
<div class="event">
  <%= link_to gravatar_for(event.user, options = {size: 95, image_icon: 'monsterid'}), event.user %>
  <div><%= link_to event.title, event %>
    <span id="event-attend-overview-<%= event.id %>" title="Confirmed attending / Invited"><%= render partial: 'attend_overview', locals: {event_invites: event.event_invites} %></span>
  </div>
  <div class="event-date"><%= event.start_time.blank? ? '' : event.start_time.strftime('%d %B %Y - %H:%M') %>
    <i class="icon-calendar"></i></div>
  <% unless event.location.blank? %>
      <div class="event-location"><%=link_to event.location, "http://maps.google.com/?q=#{event.location}" %> <i class="icon-map-marker"></i></div>
  <% end %>
  <% if current_user?(event.user) %>
      <div class="event-organizer"><%= link_to 'You', event.user %>
        <span class="username"> are organizer </span>
        <% if @user_rank[event.user.id] %> <div class="app-icon <%= rank_color_class(@user_rank[event.user.id]) %>" title="Rank based on activity the latest month"></div><% end %></div>
  <% else %>
      <div class="event-organizer"><%= link_to event.user.name, event.user %>
        <span class="username"> invited you </span></div>
  <% end %>
  <%= form_for(event.event_invites.find_by_user_id(current_user.id), remote: true) do |f| %>
      <%= f.submit 'Join', class: 'submitLink' %>
      -
      <%= f.submit 'Maybe', class: 'submitLink' %>
      -
      <%= f.submit 'Decline', class: 'submitLink' %> -
      <div id="event-reply-status-<%= event.id %>" class='no_clear'><%= render partial: 'attend_status', locals: {status: event.event_invites.find_by_user_id(current_user.id).attend_status} %> </div>
  <% end %>

  <% if current_user?(event.user) %>
      <%= link_to 'edit', [:edit, event] %> |
  <% end %>
  <% if current_user.admin? || current_user?(event.user) %>
      <%= link_to 'delete', event, method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>

</div>

app/views/events/_event_comment_list.html.erb
<ul class="event_comments">
  <% @event.event_comments.each do |c| %>
      <li>
        <%= link_to gravatar_for(c.user), c.user %>
        <span class="user">
                    <%= link_to c.user.name, c.user %>
          <span class="username">@<%= c.user.username %></span>
          <% if @user_rank[c.user.id] %> <div class="app-icon <%= rank_color_class(@user_rank[c.user.id]) %>" title="Rank based on activity the latest month"></div><% end %>
                </span>
        <span class="content"><%= format_msg(c.content).html_safe %></span>
                <span class="timestamp">
                  Posted <%= time_ago_in_words c.created_at %> ago
                </span>
        <% if current_user?(c.user) %>
            <%= link_to 'delete', [@event, c], method: :delete, data: {confirm: 'Are you sure?'}, title: c.content %>
        <% end %>
      </li>
  <% end %>
</ul>

app/views/events/_shared_input.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @event do |f| %>
        <%= render 'shared/error_messages', object: @event %>
        <%= f.label :name, 'Title' %>
        <%= f.text_field :title, size: 250 %>

        <%= f.label :location %>
        <%= f.text_field :location, size: 250 %>

        <%= f.label :start_time %>
        <div class="input-append date form_datetime">
          <%= f.text_field :start_time, readonly: true, size: 16, class: 'event_date_time',
                           value: (@event.start_time.blank? ? '' : @event.start_time.strftime('%d %B %Y - %H:%M')) %>
          <span class="add-on"><i class="icon-th"></i></span>
        </div>

        <%= f.label :end_time %>
        <div class="input-append date form_datetime">
          <%= f.text_field :end_time, readonly: true, size: 16, class: 'event_date_time',
                           value: (@event.end_time.blank? ? '' : @event.end_time.strftime('%d %B %Y - %H:%M')) %>
          <span class="add-on"><i class="icon-th"></i></span>
        </div>

        <%= f.text_area :invitation, placeholder: 'Write invitation here...' %>
        <div class="space-bottom">
          <%= f.check_box(:send_mail, checked: true) %>
          <%= f.label(:send_mail, 'Send email', class: 'label-inline') %> &nbsp;
        </div>
        <hr/>
        <div class="space-bottom">

          <div id="people-to-invite">
            <h3>Pick people to invite</h3>
            <br/>

            <div><input type="checkbox" class="checkall"> <strong>Check all</strong></div>

            <%= f.collection_check_boxes :user_ids, User.where('id != ?', current_user.id).to_a, :id, :name do |b| b.label('data-value': b.value) { b.check_box + ' ' + b.text } end%>


          </div>

          <hr/>
          <%= f.submit 'Save', class: 'btn btn-large btn-primary' %>
    <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<% provide(:title, 'Edit event!') %>

<h1>Edit event!</h1>
<%= render 'shared_input' %>

app/views/events/index.html.erb
<% provide(:title, 'All upcoming events') %>

<h1>All upcoming events!</h1>

<% if @events.empty? %>
    <h3>Sorry, no events planned :-/</h3>
<% else %>
    <div class="events">
      <%= render @events %>
    </div>
<% end %>
<hr>
<strong><%= link_to 'Create new event', new_event_path %></strong>
<br/>
<br/>
<%= link_to 'See old events', old_events_path%>
<%= will_paginate %>

app/views/events/invite.html.erb
<h2 style="font-weight:300;line-height:1.2em;text-align:center" align="center">
  <%= render 'shared/email_gravatar' %>
  <br>
  <%= @event.user.name %>
  <br> Just invited you!
</h2>
<p>Hey there, </p>
<p><%= @event.user.name %> just invited you to the event
  <a href='<%= get_url %>/events/<%= @event.id %>' target='_blank' style='color:#007fb6;text-decoration:none'><%= @event.title %></a>
</p>
<p>Please take the time to answer this invite</p>
<p style="margin-bottom:0">

app/views/events/mention.html.erb
<h2 style="font-weight:300;line-height:1.2em;text-align:center" align="center">
  <%= render 'shared/email_gravatar' %>
  <br>
  <%= @event_comment.user.name %>
  <br> Mentioned you!
</h2>
<p>Hey there, </p>
<p><%= @event_comment.user.name %> just mentioned you in:
  <a href='<%= get_url %>/events/<%= @event_comment.event.id %>' target='_blank' style='color:#007fb6;text-decoration:none'><%= @event_comment.event.title %></a>
</p>
<p style="margin-bottom:0">
<blockquote style="color:#666666;font-family:Georgia,Times New Roman,sans-serif;font-size:16px;font-style:italic;line-height:1.4;margin:30px">“<%= @event_comment.content %>”
</blockquote>

app/views/events/new.html.erb
<% provide(:title, 'Create event!') %>

<h1>Create new event!</h1>
<%= render 'shared_input' %>

app/views/events/old.html.erb
<% provide(:title, 'Old events') %>

<h1>Event history!</h1>

<% if @events.empty? %>
    <h3>No old events found </h3>
<% else %>
    <div class="events">
      <%= render @events %>
    </div>
<% end %>
<hr>
<%= link_to 'See new events', events_path %>
<%= will_paginate %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<h1>Event</h1>
<div class="row">
  <div class="span6 offset3">
    <div class="well event">
      <h3> <%= @event.title %></h3>
      <hr/>
      <div>
        <%= link_to gravatar_for(@event.user, options = {size: 50, image_icon: 'monsterid'}), @event.user %>
        <% if current_user?(@event.user) %>
            <div class="event-organizer"><%= link_to 'You', @event.user %>
              <span class="username"> are organizer </span>
              <% if @user_rank[@event.user.id] %> <div class="app-icon <%= rank_color_class(@user_rank[@event.user.id]) %>" title="Rank based on activity the latest month"></div><% end %></div>
        <% else %>
            <div class="event-organizer"><%= link_to @event.user.name, @event.user %>
              <span class="username"> invited you </span>
              <% if @user_rank[@event.user.id] %> <div class="app-icon <%= rank_color_class(@user_rank[@event.user.id]) %>" title="Rank based on activity the latest month"></div><% end %></div>
        <% end %>
      </div>

      <% if @event.location.blank? %>
          <p>Not specified yet <i class="icon-map-marker"></i></p>
      <% else %>
          <div><%= link_to @event.location, "http://maps.google.com/?q=#{@event.location}" %>
          <i class="icon-map-marker"></i></div>
      <% end %>

      <span class="event-label">Start: </span> <%= @event.start_time.blank? ? '' : @event.start_time.strftime('%A %d. %B %Y - %H:%M') %>
      <i class="icon-calendar"></i></p>

      <p>
        <span class="event-label">End: </span><%= @event.end_time.blank? ? '' : @event.end_time.strftime('%A %d. %B %Y - %H:%M') %>
        <i class="icon-calendar"></i></p>


      <%= render partial: 'events/attend_status_list' %>

      <p><span class="event-label">Invitation:</span>

      <div class="well"><%= simple_format(@event.invitation) %></div>
      </p>
      <% if current_user?(@event.user) %>
          <%= link_to 'edit', [:edit, @event] %> |
      <% end %>
      <% if current_user.admin? || current_user?(@event.user) %>
          <%= link_to 'delete', @event, method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>

    <%= render 'shared/error_messages', object: @event_comment %>
    <%= form_for @event_comment, {url: event_event_comments_path(@event.id)} do |f| %>
        <%= content_tag 'div', class: 'field', id: 'comment-input', data: {url: User.order('users.username').load.collect { |u| "#{u.username} - #{u.name}" }} do %>
            <%= f.text_area :content, placeholder: 'Write new comment...', rows: 5, class: 'message' %>
        <% end %>
        <%= f.submit 'Comment', class: 'btn btn-primary' %>
        <span class="countdown"></span>
    <% end %>

    <% unless @event.event_comments.empty? %>
        <%= render partial: 'events/event_comment_list' %>
    <% end %>
  </div>
</div>