config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :who_likes] do
    resources :likes, only: [:create, :destroy]
    member do
      get :who_likes
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :event_invites
  resources :events do
    collection do
      get :old
    end
    resources :event_comments, only: [:create, :destroy]
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new', via: :get
  match '/forgotten_password', to: 'users#forgotten_password', via: :get
  match '/send_password_link', to: 'users#send_password_link', via: :post
  match '/reset_password/:uuid', to: 'users#show_reset_password', via: :get
  match '/reset_password', to: 'users#reset_password', via: :post
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help', via: :get
  match '/contact', to: 'static_pages#contact', via: :get
  match '/about', to: 'static_pages#about', via: :get

end

app/views/layouts/_event_header.html.erb
<%= link_to raw(events_summary), events_path, title: 'Awaiting reply / Attending / Total upcoming ' %>

app/views/layouts/_event_header_mobile.erb
<%= link_to raw(event_mobile_summary), events_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
      Copyright
    </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'twittosocial', root_path, id: 'logo' %>

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <% if signed_in? %>
      <div id="nav-event-mobile">
        <ul class="nav pull-right">
            <li class="event-header-mobile"><%= render partial: 'layouts/event_header_mobile' %></li>
        </ul>
      </div>
      <% end %>

      <div class="nav-collapse">
        <ul class="nav pull-right">
          <% if signed_in? %>
              <li class="event-header"><%= render partial: 'layouts/event_header' %> </li>
              <li><%= link_to 'Help', help_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to 'Sign out', signout_path, method: 'delete' %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to 'Sign in', signin_path %></li>
          <% end %>
        </ul>
        <% if signed_in? %>
            <%= form_tag root_path, method: :get, class: 'pull-right global-search' do %>
                <p>
                  <%= text_field_tag :q, params[:q], placeholder: 'Search', id: 'nav-search-field' %>
                </p>
            <% end %>
        <% end %>
      </div>

    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script scr="http://html5shim.google.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title))%> </title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="Description" content="Open Source social network for small groups">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35910319-1']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  </script>
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="touch-icon-iphone.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="touch-icon-ipad.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="touch-icon-iphone-retina.png" />
  <link rel="apple-touch-icon" sizes="144x144" href="touch-icon-ipad-retina.png" />
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container main-content">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%=  render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
</head>
<body>
<div style="background:whitesmoke" bgcolor="whitesmoke">
  <div style="background:whitesmoke;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:20px 10px;text-align:center" align="center">
    <table width="100%" style="border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:600px;width:100%">
      <tbody>
      <tr>
        <td style="color:#999999;font-size:13px;margin-bottom:0;margin-top:0;padding:20px;text-align:center" align="center">
          <h1 style="margin:0"><img src="<%= get_url %>/SmallLogo.png"></h1>
        </td>
      </tr>
      <tr>
        <td style="background:white;color:#333333;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:15px;line-height:1.4em;padding-bottom:40px;text-align:left" align="left" bgcolor="white">
          <div style="margin-bottom:0;margin-top:0;padding:20px">
            <%= yield %>
            <br>— Your friends at <span class="il">Twittosocial</span>
            </p>

          </div>
        </td>
      </tr>
      </tbody>
    </table>
  </div>

  <img src="https://ci4.googleusercontent.com/proxy/1SF-ArwOOnsjrvjcSY05vDd1lQLa8IHNJMWcyYRPumCg5BLUrqZ35tRpOvsgZ2tVGtVKrtMFIOIzMni-Ixxg-MJq0DumLkMT8skx2F6D9RjpKZBq3lXTgELmmsTb51ibatpXLEAqjogWXioie0Dtxk-j81xY79oLRHbNoIhpEJo1Nf2_jKcYjEq83tVstV7tnfnilUYcUL6kt6sPpteVqd4rtyvpdeBMiKKAkmentXUi7l6pSZIzj5RI2LnJKWOCla67Fq4wc34Z1H1Lmy1iepDUeie6F_ExsLKvHCeHXtMNvIDiEoueSdr_i80T8yqlgPoxZvLwc4qhu6j31K0VkCZyeGMMiDFqSW7HRgHd38Rwdn9fMZ3HTFS4h7BYkADlW-hJB6_YBx-JY45CgwtxVEPvwRUP6FQyLqmGcTY2b_R1wTtklgVyHs0=s0-d-e1-ft#http://email.strava.com/wf/open?upn=EEW13zekVXfoTZUg3N-2BPu7PhScri8jHKTD6FQtWLsvOjS4bg87RJCNRRi-2F-2FsPnoJ13mZMcmlEOdPPTeuE3QMbDoYRSAQ0hiSIPSruC8hHuYuLO88aPwaX18zYwW1ulLKEKkuvm2-2BGPziADDgjoGptYyBxNNaDflme3nDAVLShX3YvnmwMTul2ZNzX3r2yJQJMhRZ4pDlOMb2ozmvFWElkxZk7V6MpgvGUJMUOLLXG5Ah-2FKrBPnAezmPk-2B6c7u8-2Bh" alt="" width="1" height="1" border="0" style="min-height:1px!important;width:1px!important;border-width:0!important;margin-top:0!important;margin-bottom:0!important;margin-right:0!important;margin-left:0!important;padding-top:0!important;padding-bottom:0!important;padding-right:0!important;padding-left:0!important">
  <div class="yj6qo"></div>
  <div class="adL">
  </div>
</div>
</body>
</html>